In [1]:
import numpy as np
import pandas as pd
import sklearn.datasets as ds

#Data preperation
rng = np.random.default_rng(42)

iris_bunch = ds.load_iris(as_frame=True)
iris = pd.DataFrame(iris_bunch.data.to_numpy(), index=np.arange(1, 151), columns=iris_bunch.data.columns)
iris_sepal_length = iris['sepal length (cm)']
iris_sepal_length_b = pd.Series(iris['sepal length (cm)'], index=np.arange(1, 151))
#@copilot: create a dataframe with the countries of europe as the index, with a column population and gbp
countries = ['France', 'Germany', 'Italy', 'Spain', 'Portugal', 'Greece', 'Belgium', 'Netherlands', 'Luxembourg', 'Austria', 'Switzerland', 'Denmark', 'Sweden', 'Norway', 'Finland', 'Iceland', 'Ireland', 'United Kingdom']
population = [67, 83, 60, 47, 10, 11, 11, 17, 0.6, 9, 8, 6, 10, 5, 5, 0.3, 5, 67]
GDP = [2.78, 4.42, 2.08, 1.39, 0.23, 0.18, 0.53, 0.91, 0.06, 0.45, 0.70, 0.35, 0.53, 0.40, 0.27, 0.02, 0.33, 2.83]

national_dept = pd.Series([2.36, 2.09, 2.34, 1.18, 2.32], index=['France', 'Belgium', 'Italy', 'Austria', 'Monaco'])
europe = pd.DataFrame({'population': population, 'GDP': GDP}, index=countries)
europe.sort_index(inplace=True)
europe_correction= rng.choice([0.99, 0.98,1.01,1], size=18)


a. Add a column to the dataframe GDP_per_capita which is the GDP divided by the population. Check the result.

b. Create a series national_dept_per_capita with the same index as the dataframe europe, which is the national_dept divided by the population. Check the result.

c. Create a series national_dept_per_capita_b with the same index as the dataframe europe, which is the national_dept divided by the population. When indexes don't align, the result should be set to 0. Check the result.

d. add national_dept and national_dept_per_capita_b to the dataframe europe

e. All numbers in the dataframe have to corrected, by multiplying every row with the corresponding value in europe_correction.

f. population, GDP and national_dept are in billions.Create a new dataframe europe_c with these columns adjusted. Check the result.

In [3]:
# a. Add a column to the dataframe GDP_per_capita which is the GDP divided by the population. Check the result.
europe['GDP_per_capita'] = europe['GDP'] / europe['population']
print(europe)

                population   GDP  GDP_per_capita
Austria                9.0  0.45        0.050000
Belgium               11.0  0.53        0.048182
Denmark                6.0  0.35        0.058333
Finland                5.0  0.27        0.054000
France                67.0  2.78        0.041493
Germany               83.0  4.42        0.053253
Greece                11.0  0.18        0.016364
Iceland                0.3  0.02        0.066667
Ireland                5.0  0.33        0.066000
Italy                 60.0  2.08        0.034667
Luxembourg             0.6  0.06        0.100000
Netherlands           17.0  0.91        0.053529
Norway                 5.0  0.40        0.080000
Portugal              10.0  0.23        0.023000
Spain                 47.0  1.39        0.029574
Sweden                10.0  0.53        0.053000
Switzerland            8.0  0.70        0.087500
United Kingdom        67.0  2.83        0.042239

In [18]:
# b. Create a series national_dept_per_capita with the same index as the dataframe europe, which is the national_dept divided by the population. Check the result.
national_dept_per_capita = pd.Series(national_dept / europe['population'], index=europe.index) #pd.Series(national_dept/population, europe.index)
print(national_dept_per_capita)

Austria           0.131111
Belgium           0.190000
Denmark                NaN
Finland                NaN
France            0.035224
Germany                NaN
Greece                 NaN
Iceland                NaN
Ireland                NaN
Italy             0.039000
Luxembourg             NaN
Netherlands            NaN
Norway                 NaN
Portugal               NaN
Spain                  NaN
Sweden                 NaN
Switzerland            NaN
United Kingdom         NaN
dtype: float64

In [21]:
# c. Create a series national_dept_per_capita_b with the same index as the dataframe europe, which is the national_dept divided by the population. When indexes don't align, the result should be set to 0. Check the result.
national_dept_per_capita_b = pd.Series(national_dept.divide(europe['population'], fill_value=0), index=europe.index)
print(national_dept_per_capita_b)

Austria           0.131111
Belgium           0.190000
Denmark           0.000000
Finland           0.000000
France            0.035224
Germany           0.000000
Greece            0.000000
Iceland           0.000000
Ireland           0.000000
Italy             0.039000
Luxembourg        0.000000
Netherlands       0.000000
Norway            0.000000
Portugal          0.000000
Spain             0.000000
Sweden            0.000000
Switzerland       0.000000
United Kingdom    0.000000
dtype: float64

In [22]:
# d. add national_dept and national_dept_per_capita_b to the dataframe europe
europe['national_dept'] = national_dept
europe['national_dept_per_capita_b'] = national_dept_per_capita_b
europe

,population,GDP,GDP_per_capita,national_dept,national_dept_per_capita_b
Austria,9.0,0.45,0.050000,1.18,0.131111
Belgium,11.0,0.53,0.048182,2.09,0.190000
Denmark,6.0,0.35,0.058333,NaN,0.000000
Finland,5.0,0.27,0.054000,NaN,0.000000
France,67.0,2.78,0.041493,2.36,0.035224
Germany,83.0,4.42,0.053253,NaN,0.000000
Greece,11.0,0.18,0.016364,NaN,0.000000
Iceland,0.3,0.02,0.066667,NaN,0.000000
Ireland,5.0,0.33,0.066000,NaN,0.000000
Italy,60.0,2.08,0.034667,2.34,0.039000
Luxembourg,0.6,0.06,0.100000,NaN,0.000000
Netherlands,17.0,0.91,0.053529,NaN,0.000000
Norway,5.0,0.40,0.080000,NaN,0.000000
Portugal,10.0,0.23,0.023000,NaN,0.000000
Spain,47.0,1.39,0.029574,NaN,0.000000
Sweden,10.0,0.53,0.053000,NaN,0.000000
Switzerland,8.0,0.70,0.087500,NaN,0.000000
United Kingdom,67.0,2.83,0.042239,NaN,0.000000

In [27]:
# e. All numbers in the dataframe have to corrected, by multiplying every row with the corresponding value in europe_correction.
print(europe_correction)
europe.multiply(europe_correction, axis=0)

[0.99 1.   1.01 0.98 0.98 1.   0.99 1.01 0.99 0.99 1.01 1.   1.01 1.
 1.01 1.   1.01 0.99]

,population,GDP,GDP_per_capita,national_dept,national_dept_per_capita_b
Austria,8.910,0.4455,0.049500,1.1682,0.129800
Belgium,11.000,0.5300,0.048182,2.0900,0.190000
Denmark,6.060,0.3535,0.058917,NaN,0.000000
Finland,4.900,0.2646,0.052920,NaN,0.000000
France,65.660,2.7244,0.040663,2.3128,0.034519
Germany,83.000,4.4200,0.053253,NaN,0.000000
Greece,10.890,0.1782,0.016200,NaN,0.000000
Iceland,0.303,0.0202,0.067333,NaN,0.000000
Ireland,4.950,0.3267,0.065340,NaN,0.000000
Italy,59.400,2.0592,0.034320,2.3166,0.038610
Luxembourg,0.606,0.0606,0.101000,NaN,0.000000
Netherlands,17.000,0.9100,0.053529,NaN,0.000000
Norway,5.050,0.4040,0.080800,NaN,0.000000
Portugal,10.000,0.2300,0.023000,NaN,0.000000
Spain,47.470,1.4039,0.029870,NaN,0.000000
Sweden,10.000,0.5300,0.053000,NaN,0.000000
Switzerland,8.080,0.7070,0.088375,NaN,0.000000
United Kingdom,66.330,2.8017,0.041816,NaN,0.000000

In [38]:
# f. population, GDP and national_dept are in billions.Create a new dataframe europe_c with these columns adjusted. Check the result.
# europe_c = pd.DataFrame(europe * 1_000_000_000)
europe[['population', 'GDP', 'national_dept']] *= 1e9 # remember [columns, rows] so if you did ['population', 'GDP'] --> error cause GDP row doesn't existe
print(europe)

                  population           GDP  GDP_per_capita  national_dept  \
Austria         9.000000e+27  4.500000e+26        0.050000   1.180000e+27
Belgium         1.100000e+28  5.300000e+26        0.048182   2.090000e+27
Denmark         6.000000e+27  3.500000e+26        0.058333            NaN
Finland         5.000000e+27  2.700000e+26        0.054000            NaN
France          6.700000e+28  2.780000e+27        0.041493   2.360000e+27
Germany         8.300000e+28  4.420000e+27        0.053253            NaN
Greece          1.100000e+28  1.800000e+26        0.016364            NaN
Iceland         3.000000e+26  2.000000e+25        0.066667            NaN
Ireland         5.000000e+27  3.300000e+26        0.066000            NaN
Italy           6.000000e+28  2.080000e+27        0.034667   2.340000e+27
Luxembourg      6.000000e+26  6.000000e+25        0.100000            NaN
Netherlands     1.700000e+28  9.100000e+26        0.053529            NaN
Norway          5.000000e+27  4.000000e+26        0.080000            NaN
Portugal        1.000000e+28  2.300000e+26        0.023000            NaN
Spain           4.700000e+28  1.390000e+27        0.029574            NaN
Sweden          1.000000e+28  5.300000e+26        0.053000            NaN
Switzerland     8.000000e+27  7.000000e+26        0.087500            NaN
United Kingdom  6.700000e+28  2.830000e+27        0.042239            NaN

                national_dept_per_capita_b
Austria                           0.131111
Belgium                           0.190000
Denmark                           0.000000
Finland                           0.000000
France                            0.035224
Germany                           0.000000
Greece                            0.000000
Iceland                           0.000000
Ireland                           0.000000
Italy                             0.039000
Luxembourg                        0.000000
Netherlands                       0.000000
Norway                            0.000000
Portugal                          0.000000
Spain                             0.000000
Sweden                            0.000000
Switzerland                       0.000000
United Kingdom                    0.000000